### ISSUE TITLE
Docker安装Jenkins

### ISSUE THREAD

**Issue by leniNikky** [leniNikky/blogs#4]
在docker安装容器的时候容易遇到的两个问题  
1.port is already allocated(端口被指派了)  
解决办法：改端口  
2.that container to be able to reuse that name  
解决办法：查看（删除）之前的容器  
```
docker ps -a | grep jenkins_imooc // -a是把没运行的也列出来 （不确定哈）
docker rm jenkins_imooc
```

 启动docker服务
 
```
sudo systemctl start docker
```
vi /home/jenkins/docker-compose.yml，创建docker-compose.yml

```yml
version: '3'
services:
  jenkins: 
    container_name: 'jenkins'
    image: jenkins/jenkins:lts
    restart: always
    user: jenkins:994
    ports: 
    - "11005:8080"
    - "50000:50000"
    - "10051:10051"
    volumes:
    - /home/jenkins/data:/var/jenkins_home
    - /usr/bin/docker:/usr/bin/docker
    - /var/run/docker.sock:/var/run/docker.sock
```
如果之前没有这个文件，修改完就保存不了了，把vi改为vim

下面是安装步骤
* 到[github](
https://github.com/jenkinsci/docker)复制命令
```
docker run -p 8080:8080 -p 50000:50000 jenkins/jenkins:lts
```
* 打开终端，使用ssh连接到远程测试服务器  

* 粘贴上面那句命令，修改默认的8080端口，映射到其他的宿主机端口，并指定容器名称，按回车，如果顺利的话会打印出一串哈希值
```
docker run --name jenkins_im -itd  -p 11005:8080 -p 50000:50000 jenkins/jenkins:lts // -itd:增加交互式终端，并让这句命令让docker在后台执行
```
* 执行如下命令，查看容器是否运行
```
docker ps | grep jenkins_im
```
* 执行如下命令，打印容器里面的信息，会看到一个管理员的密码，把它保存下来，后面会用到，ctrl+c退出log命令
```
docker logs -f jenkins_im
```
* 如果防火墙没关，让防火墙放行上面设置的11005端口
```
firewall-cmd --add-port=11005/tcp --permanent
```
* 然后重新加载防火墙
```
firewall-cmd --reload
```

这时就可以在浏览器范围虚拟机的ip加端口号就可以访问了。接下来的操作就是：  
* 输入刚才保存的管理员密码  

* 选择安装推荐的插件

* 如果看到离线提醒，可能是前面设置的ip不能访问谷歌的服务，有些插件需要访问谷歌下载安装，解决办法就是设置代理，要不就离线安装，可配置清华加速源下载插件  

* 创建一个管理员账号  

* 实例配置会有个url，在以后跟gitlab连接的时候需要使用到这个地址，如果需要修改可以在系统的设置里修改

* 登录进去之后在系统管理的插件管理（manage plugins）的高级（advanced）里配置升级站点（update site）的url，什么url呢，就是[清华开源镜像的update-center.json的链接](https://mirrors.tuna.tsinghua.edu.cn/jenkins/updates/)

* 如果要去官网下载相关插件，下载完之后点击这里的上传插件就可以安装了。

* 下次再把容器跑起来
```
docker start <container name>
```
